### ISSUE TITLE
Serializable beans into Sessions

### ISSUE THREAD

**Issue by pascalheraud** [auth0/auth0-servlet#34]
Bean that are put in session should be Serializable.
It's not mandatory but Servlet Engines like Tomcat store sessions on disk when stopping.

So Auth0User and Tokens should be Serializable.

I can provide a fix if you want it.

**Comment by ygorgasparin** [comment]
I'am getting

> java.lang.IllegalArgumentException: PWC2788: setAttribute: Non-serializable attribute with name auth0tokens
>         at org.apache.catalina.session.ManagerBase.checkSessionAttribute(ManagerBase.java:832)
>         at org.apache.catalina.session.StandardSession.setAttribute(StandardSession.java:1713)
>         at org.apache.catalina.session.StandardSessionFacade.setAttribute(StandardSessionFacade.java:178)
>         at com.auth0.Auth0ServletCallback.store(Auth0ServletCallback.java:103)
On Glassfish.

**Comment by pascalheraud** [comment]
A status about it ?

**Comment by pascalheraud** [comment]
Ok, it is fixed in the 3.0.0 release.
We upgraded to this new release.
(warning : major differences between 2.x and 3.x).

**Comment by arcseldon** [comment]
@pascalheraud - pleased to see this resolved. Please let me know if you have any issues with the upgrade etc - be happy to help you directly.
